### ISSUE TITLE
API Change

### ISSUE THREAD

**Issue by marco123445** [da4id/OctoPrint-MyStromSwitch#18]
Hi could it be that something with the raw data string from the API has changedt and the plugin is not working anymore. I had this problem with Node-red?

**Comment by da4id** [comment]
Please provide some more Information

- Which Firmware Version do you have on the switch (enter http://[IP of your mySwitch] in your webbrowser)
- is http://[IP of your mySwitch] reachable?
- try http://[IP of your mySwitch]/report ans post result here
- Did the IP of your switch changed? Do you setthe correct IP in the Plugin?
- What exactly does not work?

My mySwitch uses Firmwareversion 3.82.4 it seems that this is the newest. In the API documentation is no change noticed. I don't think that there changed anything. 

You wrote that you had the same Problem with Node-red. I think that theres a network Problem on your side. MySwitch uses normally DHCP IP Adress assignment. Therefore the IP could change from time to time.
