### ISSUE TITLE
Turn on/off button missing [PrusaPrint]

### ISSUE THREAD

**Issue by kalmard0** [da4id/OctoPrint-MyStromSwitch#23]
Even though I've enabled it in the settings, the button is missing from the UI.

**Comment by da4id** [comment]
Check #22. Maybe your IP Settings are wrong. Enter IP Adress without http://
When you turn on your switch do you see some power consumption?

**Comment by kalmard0** [comment]
Thank you, that solved it.
The setting field literally says **URL** or IP address, so I think it's quite confusing that you can't add the http part.
