### ISSUE TITLE
Python 3 Compatibility

### ISSUE THREAD

**Issue by cp2004** [da4id/OctoPrint-MyStromSwitch#25]
I don't use this plugin, but am doing the rounds on the OctoPrint plugin repository to help upgrade to Python 3. So, here's a heads up:
As you are probably aware, OctoPrint currently supports Python 2 & 3 simultaneously. Users will begin migrating to Python 3 soon and your plugin will not be installable. As of March 2021, it will switch to Python 3 only.
Please see the guide [here](https://docs.octoprint.org/en/master/plugins/python3_migration.html)

If you want any help updating the plugin let me know.

**Comment by cp2004** [comment]
Hey @da4id, I just got the notification that you closed this. Assume the plugin is fully compatible and tested, if so do you want me to update the plugin repo?
Nice work, adding Python 3 compatibility can be right a pain especially supporting both simultaneously.

**Comment by da4id** [comment]
Hi, yes plugin works now with python3! Of course you can update the plugin repo
